/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ChatItem.module.css";

const ChatItem = ({ avatar, userName, timestamp, lastMessage, isPinned }) => {
  const itemClass = `${styles.chatItem} ${isPinned ? styles.pinnedItem : ""}`;

  return (
    <div className={itemClass}>
      <img
        src={avatar}
        alt={`${userName}'s avatar`}
        className={styles.avatar}
      />
      <div className={styles.chatContent}>
        <div className={styles.chatHeader}>
          <div className={styles.userName}>{userName}</div>
          <div className={styles.timestamp}>{timestamp}</div>
        </div>
        <div className={styles.lastMessage}>{lastMessage}</div>
      </div>
    </div>
  );
};

export default ChatItem;
