/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ChatList.module.css";
import ChatItem from "./ChatItem";

const ChatList = () => {
  const pinnedChats = [
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/992fade9561245879a3a91161565a5ca749b13b65a14aab82dd6245318eb8381?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Ahmed Abdelhady",
      timestamp: "1:47 PM",
      lastMessage: "I reviewed with Ibrahim alnaghy and he//",
    },
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ed2016223f78368fcaf8d3dbdd223661c6ca1d34fa6d803e755ea1845bbec749?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Mahmoud Alaam",
      timestamp: "1:43 PM",
      lastMessage: "Thanks, that would be great.",
    },
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/50be841be5ca419f1404ffee2681700b98768987fc39a88813bc14509a5ecaa5?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Fatima Al Oraby",
      timestamp: "Yesterday",
      lastMessage: "I haven't checked available time...",
    },
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/7ca43e62cb6a0d30d7d17f6d60c3faa402d9ddfcc545c8f40549ad87880187e5?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Malek Al Battah",
      timestamp: "12:00 PM",
      lastMessage: "Yes, please proceed.",
    },
  ];

  const recentChats = [
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/445efa3d87169d38f373a111149072d6fc7e6b80b3c330de42bfe92c24a304f8?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Emiliano Ceballos",
      timestamp: "1:47 PM",
      lastMessage: "I reviewed with Ibrahim alnaghy and he ..",
    },
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ff84f94841e4c2dbdc8cc5aa627505fe286dd2ec0415c7e30569c2300bf46f1c?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Marie Beaudouin",
      timestamp: "1:43 PM",
      lastMessage: "Sounds good?",
    },
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/658db38cee5a2d0cb53680b0c3a1049e866be55265776afc2a969bc489c0202d?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Alice Wonder",
      timestamp: "1:43 PM",
      lastMessage: "I haven't checked available time...",
    },
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/c575fb98fac7836e951759eb9a70e8ff538a405c780c999e916a018f0e24f2cb?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Oscar Krogh",
      timestamp: "Yesterday",
      lastMessage: "Yes, please proceed.",
    },
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/641586ed7b1bf20b05b00932564f8140f66b0e7b44fae4a4319195bbb64b3bf9?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Kevin Daniel",
      timestamp: "Yesterday",
      lastMessage: "I haven't checked available time...",
    },
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/7bfe7ae454f0f49684a0f51337970c4fa27d5340a63ac9c0ffeb102905364223?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Adel Ibraheem",
      timestamp: "12:00 PM",
      lastMessage: "Yes, please proceed.",
    },
    {
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/945638a2d1d2bf80b40190aa1267dbaada80f2d1050ce143a1f176224767f139?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
      userName: "Kian Lambert",
      timestamp: "12:00 PM",
      lastMessage: "I haven't checked available time...",
    },
  ];

  return (
    <section className={styles.chatList}>
      <header className={styles.header}>
        <div className={styles.headerTitle}>
          <h2>Chat</h2>
          <span className="fa fa-angle-down" aria-hidden="true"></span>
        </div>
        <div className={styles.headerIcons}>
          <span className="fa fa-bars-filter" aria-hidden="true"></span>
          <span className="fa fa-pen-to-square" aria-hidden="true"></span>
        </div>
      </header>

      <div>
        <h3 className={styles.sectionTitle}>
          <span className="fa fa-angle-down" aria-hidden="true"></span>
          Pinned
        </h3>
        <div className={styles.chatItemList}>
          {pinnedChats.map((chat, index) => (
            <ChatItem key={`pinned-${index}`} {...chat} isPinned={true} />
          ))}
        </div>
      </div>

      <div>
        <h3 className={styles.sectionTitle}>
          <span className="fa fa-angle-down" aria-hidden="true"></span>
          Recent
        </h3>
        <div className={styles.chatItemList}>
          {recentChats.map((chat, index) => (
            <ChatItem key={`recent-${index}`} {...chat} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default ChatList;
