/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ActionPanel from "../ActionPanel/ActionPanel";
import '../CustomizeHeader.css';

const NotificationCard = () => {
  return (
    <section className="flex flex-col justify-center px-3 py-3 rounded-xl shadow-sm backdrop-blur-[50px] bg-white bg-opacity-10">
      <div className="flex flex-col">
        <h2 className="text-sm font-medium font-['Inter'] font-Avenir-Medium text-gradient" >
          Let me know once you are done.
        </h2>
        <ActionPanel />
      </div>
    </section>
  );
};

export default NotificationCard;
