/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex flex-wrap gap-10 items-start mt-6 w-full max-w-[1204px] max-md:max-w-full">
      <div className="flex flex-col self-end mt-36 max-md:mt-10">
        <div className="flex gap-2.5 items-center self-start text-slate-300">
          <span className="self-stretch my-auto text-sm font-extrabold">
            Pause animation
          </span>
          <span className="self-stretch my-auto text-xs font-black">Pause</span>
        </div>
        <p className="mt-4 text-xs font-[350] text-neutral-500">
          Copyright © 2024 Sharjah Digital Department, All Rights Reserved.
        </p>
      </div>
      
    </footer>
  );
}

export default Footer;
