/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex z-10 flex-wrap gap-5 justify-between self-stretch w-full text-base whitespace-nowrap max-md:max-w-full">
      <div className="flex gap-2 items-center self-start">
        <div className="self-stretch my-auto text-neutral-800">العربية</div>
        <span
          className="self-stretch my-auto font-light text-slate-300"
          aria-hidden="true"
        >
          globe
        </span>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8a683e1041a4bc1899ebb007eb69e17245af19a1192dab5802a940b120745b2b?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
        className="object-contain shrink-0 max-w-full aspect-[2.84] w-[210px]"
        alt="Company logo"
      />
    </header>
  );
}

export default Header;
