/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ImageSection() {
  return (
    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/957cbba75c43b7353aff96724613f67106efbaf0b3dbf402d2897d91c2f3a284?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
        className="object-contain grow w-full aspect-[0.69] max-md:mt-10 max-md:max-w-full"
        alt="Decorative illustration"
      />
      <div className="flex-auto self-start max-md:max-w-full">
      <h2 className="mt-4 text-sm font-extrabold leading-5 text-neutral-800">
        The Scroll <br /> Monumental Sculpture
      </h2>
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col ml-5 w-4/5 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow items-start text-xs font-[350] max-md:mt-10">
              <p className="self-stretch leading-3 text-zinc-400">
                The Scroll is a contemporary interpretation of the ancient
                Arabic scrolls - a single, spiralling sculpture that loops
                towards the sky.
                <br />
                <br />
                The design and inspiration are representative of a celebration
                of reading and the power of books to unite people, central to
                the purpose of the House of Wisdom and that of the UNESCO World
                <br />
                Book Capital initiative.
              </p>
              <a
                href="https://yoursharja.ae"
                className="mt-7 text-sm font-extrabold text-orange-600"
              >
                Visit yoursharja.ae
              </a>
              <p className="mt-2.5 text-neutral-500">
                To learn more about the new Sharjah's identity.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ImageSection;
