/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";
import UserActions from "./UserActions";
import styles from "./Header.module.css";

const Header = () => {
  return (
    <header className={styles.header}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/9f1ae652711b09c81cc50d2c0d7e87686d1476aaef17975546543a0b953da384?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
        alt="Company Logo"
        className={styles.logo}
      />
      <SearchBar />
      <UserActions />
    </header>
  );
};

export default Header;
