/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SearchBar.module.css";

const SearchBar = () => {
  return (
    <form className={styles.searchForm}>
      <label htmlFor="searchInput" className="visually-hidden">
        Search
      </label>
      <input
        type="search"
        id="searchInput"
        placeholder="Search"
        className={styles.searchInput}
        aria-label="Search"
      />
    </form>
  );
};

export default SearchBar;
