/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import styles from "./SearchBar.module.css";
import SearchModal from "./SearchModal";

const SearchBar = (setLgShow) => {
  
  return (
    <>
      
    <form className={styles.searchForm}>
      <label htmlFor="searchInput" className="visually-hidden">
        Search
      </label>
      <input
        type="search"
        id="searchInput"
        placeholder="Search"
        className={styles.searchInput}
        aria-label="Search"
        onClick={() => setLgShow(true)}
      />
    </form>
    </>
    
  );
};

export default SearchBar;
