/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./UserActions.module.css";

const UserActions = () => {
  return (
    <nav className={styles.userActions}>
      <button className={styles.actionButton} aria-label="Compliance">
        <span className={styles.iconWrapper}>
          <span className={styles.icon}>shield</span>
        </span>
      </button>
      <button className={styles.actionButton} aria-label="Notifications">
        <span className={styles.iconWrapper}>
          <span className={styles.icon}>bell</span>
        </span>
      </button>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a53f5fedd738f309cd216f8961ace52c2720d238f341a1a78183fc17d008927e?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
        alt="User Avatar"
        className={styles.userAvatar}
      />
      <button className={styles.menuButton} aria-label="Menu">
        bars
      </button>
    </nav>
  );
};

export default UserActions;
