/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ChatMessage.module.css";

function ChatMessage({ avatar, message }) {
  return (
    <div className={styles.chatMessage}>
      <img src={avatar} alt="User avatar" className={styles.avatar} />
      <div className={styles.messageContent}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b104a6a599de97f78e621e80d969d97b27c2cb7a56f6ef52476e0f9a1a189c17?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
          alt=""
          className={styles.messageBubble}
        />
        <p>{message}</p>
      </div>
    </div>
  );
}

export default ChatMessage;
