/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import ChatContent from "./ChatContent";
import ComposeBar from "./ComposeBar";
import styles from "./ChatRoom.module.css";

function ChatRoom() {
  return (
    <main className={styles.chatRoom}>
      <section className={styles.chatContainer}>
        <div className={styles.canvas}>
          <Header />
          <ChatContent />
        </div>
      </section>
      <ComposeBar />
    </main>
  );
}

export default ChatRoom;
