/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ChatMessage from "./ChatMessage";
import BotIntroduction from "./BotIntroduction";
import styles from "./ChatContent.module.css";

function ChatContent() {
  return (
    <section className={styles.chatContent}>
      <div className={styles.messageContainer}>
        <ChatMessage
          avatar="https://cdn.builder.io/api/v1/image/assets/TEMP/0cc7817d18ded7d01a1a0dee7f02b4ea27b6adc15d98bff887e7ca37d4565c61?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
          message="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
        />
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/63b03f1c09e506fa00ebf9ed6cba6c58b7527c93302c01ba39b584c57c6267b6?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
          alt="Chat illustration"
          className={styles.chatIllustration}
        />
        <BotIntroduction />
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c8943699d5fb0748a9d3539390053a091154df850b485e80af36f6cc8e86ec3?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
        alt="Additional chat feature"
        className={styles.additionalFeature}
      />
    </section>
  );
}

export default ChatContent;
