/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ComposeBar.module.css";

function ComposeBar() {
  return (
    <footer className={styles.compose}>
      <div className={styles.composeProtectionLayer}>
        <div className={styles.composeBackground}>
          <form className={styles.composeForm}>
            <div className={styles.inputWrapper}>
              <label htmlFor="newMessage" className={styles.visuallyHidden}>
                Type a new message
              </label>
              <input
                type="text"
                id="newMessage"
                className={styles.messageInput}
                placeholder="Type a new message"
              />
            </div>
            <div className={styles.formFooter}>
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/97d8b37c135fba930959d1c4aa91e852829449935bfde3466e5a34b4b4a8a183?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
                alt="Additional input options"
                className={styles.inputOptions}
              />
              <button type="submit" className={styles.sendButton}>
                <img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/b9295d7d42a4374194d9c13dd001cb36d5abb6f68087fe126c9db397c57a1a30?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
                  alt="Send message"
                  className={styles.sendIcon}
                />
              </button>
            </div>
          </form>
        </div>
      </div>
    </footer>
  );
}

export default ComposeBar;
