/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

function Header() {
  return (
    <header className={styles.header}>
      <div className={styles.headerContent}>
        <div className={styles.userInfo}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/65b7b49a02381af7c19b1a1ed00a981b827c42fcbc33e599780a7a4aa8c29902?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
            alt="User avatar"
            className={styles.avatar}
          />
          <div className={styles.titleTabsStack}>
            <h1 className={styles.userName}>Ahmed Abdelhady</h1>
            <nav className={styles.tabNavigation}>
              <button className={`${styles.tab} ${styles.activeTab}`}>
                Chat
                <div className={styles.activeIndicator} />
              </button>
              <button className={styles.tab}>About</button>
            </nav>
          </div>
        </div>
        <div className={styles.actionButtons}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/bd7d612ed6d34aa4b62952dceedfc2bd470497abd4956c1a9d9fd80b797183c5?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
            alt="Action button 1"
            className={styles.actionButton}
          />
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b0f9c328febf783338b18cbbe298d76b85c46ed18e13924eae98d03093dc13a3?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746"
            alt="Action button 2"
            className={styles.actionButton}
          />
        </div>
      </div>
      <div className={styles.headerBorder} />
    </header>
  );
}

export default Header;
