/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ChatItem({ name, time, message, image }) {
  return (
    <article className="flex gap-3 items-center p-3 w-full">
      <img
        loading="lazy"
        src={image}
        alt={`${name}'s profile`}
        className="object-contain shrink-0 self-stretch my-auto rounded-3xl aspect-square w-[41px]"
      />
      <div className="flex flex-col flex-1 shrink self-stretch my-auto basis-0 min-w-[240px]">
        <div className="flex gap-10 justify-between items-start w-full text-neutral-800">
          <h3 className="text-base font-medium">{name}</h3>
          <time className="text-sm">{time}</time>
        </div>
        <p className="mt-3 text-xs font-medium text-slate-500">{message}</p>
      </div>
    </article>
  );
}

export default ChatItem;
