/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ChatHeader from "./ChatHeader";
import ChatSection from "./ChatSection";

const pinnedChats = [
  {
    id: 1,
    name: "Ahmed Abdelhady",
    time: "1:47 PM",
    message: "I reviewed with Ibrahim alnaghy and he//",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/992fade9561245879a3a91161565a5ca749b13b65a14aab82dd6245318eb8381?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
  {
    id: 2,
    name: "Mahmoud Alaam",
    time: "1:43 PM",
    message: "Thanks, that would be great.",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/ed2016223f78368fcaf8d3dbdd223661c6ca1d34fa6d803e755ea1845bbec749?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
  {
    id: 3,
    name: "Fatima Al Oraby",
    time: "Yesterday",
    message: "I haven't checked available time...",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/50be841be5ca419f1404ffee2681700b98768987fc39a88813bc14509a5ecaa5?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
  {
    id: 4,
    name: "Malek Al Battah",
    time: "12:00 PM",
    message: "Yes, please proceed.",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/7ca43e62cb6a0d30d7d17f6d60c3faa402d9ddfcc545c8f40549ad87880187e5?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
];

const recentChats = [
  {
    id: 5,
    name: "Emiliano Ceballos",
    time: "1:47 PM",
    message: "I reviewed with Ibrahim alnaghy and he ..",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/445efa3d87169d38f373a111149072d6fc7e6b80b3c330de42bfe92c24a304f8?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
  {
    id: 6,
    name: "Marie Beaudouin",
    time: "1:43 PM",
    message: "Sounds good?",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/ff84f94841e4c2dbdc8cc5aa627505fe286dd2ec0415c7e30569c2300bf46f1c?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
  {
    id: 7,
    name: "Alice Wonder",
    time: "1:43 PM",
    message: "I haven't checked available time...",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/658db38cee5a2d0cb53680b0c3a1049e866be55265776afc2a969bc489c0202d?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
  {
    id: 8,
    name: "Oscar Krogh",
    time: "Yesterday",
    message: "Yes, please proceed.",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c575fb98fac7836e951759eb9a70e8ff538a405c780c999e916a018f0e24f2cb?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
  {
    id: 9,
    name: "Kevin Daniel",
    time: "Yesterday",
    message: "I haven't checked available time...",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/641586ed7b1bf20b05b00932564f8140f66b0e7b44fae4a4319195bbb64b3bf9?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
  {
    id: 10,
    name: "Adel Ibraheem",
    time: "12:00 PM",
    message: "Yes, please proceed.",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/7bfe7ae454f0f49684a0f51337970c4fa27d5340a63ac9c0ffeb102905364223?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
  {
    id: 11,
    name: "Kian Lambert",
    time: "12:00 PM",
    message: "I haven't checked available time...",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/945638a2d1d2bf80b40190aa1267dbaada80f2d1050ce143a1f176224767f139?placeholderIfAbsent=true&apiKey=041020761c824046b3f5b318a397a746",
  },
];

function ChatComponent() {
  return (
    <main className="flex flex-col p-5 mx-auto w-full bg-white rounded-3xl max-w-[480px] font-inter">
      <ChatHeader />
      <div className="flex flex-col mt-6 w-full">
        <ChatSection title="Pinned" chats={pinnedChats} />
        <ChatSection title="Recent" chats={recentChats} />
      </div>
    </main>
  );
}

export default ChatComponent;
