/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AppCard({ name, description, isChecked, icon }) {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full bg-[#EDF0F2] rounded-xl">
      <div className="flex grow gap-4 items-start p-6 w-full bg-gray-100 rounded-xl max-md:px-5 max-md:mt-5">
        <div className="flex flex-col w-11 text-lg font-black text-white whitespace-nowrap">
          <div className="overflow-hidden flex items-center justify-center w-11 h-11 bg-sky-500 rounded-xl min-h-[44px]">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              className="w-6 h-6"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d={getIconPath(icon)}
              />
            </svg>
          </div>
        </div>
        <div className="flex flex-col flex-1 shrink basis-0">
          <div className="flex gap-10 justify-between items-center w-full whitespace-nowrap">
            <div className="self-stretch my-auto text-base font-extrabold text-black">
              {name}
            </div>
            <div
              className={`gap-2.5 self-stretch px-2 my-auto w-7 h-7 text-xs font-black text-gray-100 ${
                isChecked ? "bg-[#777FA1]" : "bg-[linear-gradient(180deg,#65C169_0%,#43A5E8_100%)]"
              } rounded-[40px] flex items-center justify-center`}
            >
             
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="#fff"
                  className="w-4 h-4"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M5 13l4 4L19 7"
                  />
                </svg>
              
            </div>
          </div>
          <div className="mt-2 text-xs text-black">{description}</div>
        </div>
      </div>
    </div>
  );
}

function getIconPath(icon) {
  switch (icon) {
    case "at":
      return "M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207";
    case "calendar":
      return "M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z";
    case "check-square":
      return "M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4";
    case "edit":
      return "M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z";
    case "hard-drive":
      return "M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6";
    case "video":
      return "M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z";
    default:
      return "";
  }
}

export default AppCard;
