/**
 * This code was generated by Builder.io.
 */
import React, { useEffect, useState } from "react";
import AppCard from "./AppCard";

const appData = [
  {
    id: 1,
    name: "Mail",
    description: "Send mass publications to your group, department, company",
    isChecked: false,
    icon: "at",
  },
  {
    id: 2,
    name: "Calendar",
    description: "Schedule meetings and manage your time efficiently",
    isChecked: true,
    icon: "calendar",
  },
  {
    id: 3,
    name: "Tasks",
    description: "Organize and track your daily tasks and projects",
    isChecked: true,
    icon: "check-square",
  },
  {
    id: 4,
    name: "Notes",
    description: "Take quick notes and sync across all your devices",
    isChecked: true,
    icon: "edit",
  },
  {
    id: 5,
    name: "Drive",
    description: "Store and share files securely in the cloud",
    isChecked: true,
    icon: "hard-drive",
  },
  {
    id: 6,
    name: "Meet",
    description: "Host video conferences and collaborate remotely",
    isChecked: true,
    icon: "video",
  },
];

function AppRecommendation() {
  const [animate, setAnimate] = useState(false);

  useEffect(() => {
    setAnimate(true);
  }, []);
  
  const proceedToHome = () => {
    
    window.location.href = '/intro'

  }
  return (
    <main className={`flex overflow-hidden flex-col items-center px-20 py-64 bg-white max-md:px-5 max-md:py-24 font-inter transition-all duration-[3600ms] ease-in-out ${
          animate
            ? "opacity-100 translate-y-0"
            : "opacity-0 translate-y-[160px]"
        }`}>
      <h1 className="text-2xl font-medium text-neutral-800 max-md:max-w-full">
        As per our records you work as frontend developer
      </h1>
      <p className="mt-0.5 text-xl mb-0 font-medium text-neutral-800 max-md:max-w-full">
        We believe these apps will make your daily work more efficient
      </p>
      <p className="mt-0.5 mb-0 text-xl font-medium text-neutral-800">
        Click subscribe to request access
      </p>
      <section className="mt-[3.7rem] max-w-full w-[916px] max-md:mt-10">
        <div className="flex gap-5 max-md:flex-col">
          {appData.slice(0, 3).map((app) => (
            <AppCard key={app.id} {...app} />
          ))}
        </div>
      </section>
      <section className="mt-5 max-w-full w-[916px]">
        <div className="flex gap-5 max-md:flex-col">
          {appData.slice(3).map((app) => (
            <AppCard key={app.id} {...app} />
          ))}
        </div>
      </section>
      <button className="flex gap-10 justify-between items-center px-6 mt-11 max-w-full text-base text-white bg-black min-h-[48px] rounded-[32px] w-[249px] max-md:px-5 max-md:mt-10">
        <span className="self-stretch my-auto font-medium" onClick={() => proceedToHome()}>
          Apply and proceed
        </span>
        <span className="self-stretch my-auto">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            className="w-4 h-4"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M14 5l7 7m0 0l-7 7m7-7H3"
            />
          </svg>
        </span>
      </button>
    </main>
  );
}

export default AppRecommendation;
