/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Nav from "react-bootstrap/Nav";
import styles from "./NavigationMenu.module.css";
import { useNavigate } from "react-router-dom";

const navigationItems = [
  { icon: "/assets/homeActive.svg", label: "/" },
  { icon: "/assets/CategoriesNotActive.svg", label: "/categories" },
  { icon: "/assets/KnowledgeNotActive.svg", label: "/services" },
  { icon: "/assets/messageNotActive.svg", label: "/teams" },
  { icon: "/assets/SupportNotActive.svg", label: "/add" },
];

const navigationItems2 = [
  { icon: "/assets/comments-question.svg", label: "/comments" },
  { icon: "/assets/life-ring.svg", label: "/support" },
];

const SideView = () => {
  let navigate = useNavigate();

  return (
    <div className={styles.navigationMenu}>
      <Nav
        defaultActiveKey="/"
        style={{
          flexDirection: "column",
          display: "flex",
          height: "100%",
          justifyContent: "center",
          rowGap: "10%",
        }}
      >
        {navigationItems.map((item, index) => (
          <div
          
            onClick={() => {
              navigate(item.label);
              // localStorage.setItem('SubHeader' , false)
            }}
          >
          
            <img style={{cursor : 'pointer'}} src={item.icon} alt="icon" />
          </div>
        ))}
      </Nav>

      <Nav
        defaultActiveKey="/"
        style={{
          flexDirection: "column",
          display: "flex",
          height: "100%",
          justifyContent: "center",
        }}
      >
        {navigationItems2.map((item, index) => (
          <Nav.Link href={item.label}>
            <img src={item.icon} alt="icon" />
          </Nav.Link>
        ))}
      </Nav>
    </div>
  );
};

export default SideView;
