/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavigationButton from "./NavigationButton";
import styles from "./NavigationMenu.module.css";

const navigationItems = [
  { icon: "/assets/homeActive.svg", label: "Home" },
  { icon: "/assets/CategoriesNotActive.svg", label: "Apps" },
  { icon: "/assets/KnowledgeNotActive.svg", label: "Services" },
  { icon: "/assets/messageNotActive.svg", label: "Teams" },
  { icon: "/assets/SupportNotActive.svg", label: "Add" },
];

const NavigationMenu = () => (
  <nav className={styles.navigationMenu}>
    {navigationItems.map((item, index) => (
      <NavigationButton
        key={item.label}
        icon={item.icon}
        isActive={index === 0}
      />
    ))}
  </nav>
);

export default NavigationMenu;
